[package]
name = "llun-cli"
version = "1.3.1"
edition = "2024"

[[bin]]
name = "llun"
path = "src/main.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rmcp = { version = "0.2.0", features = ["server"] }
llun_core = { path = "../llun_core" }